<<<<<<< HEAD
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
=======
>>>>>>> f6fc9b2 (Initial commit)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

<<<<<<< HEAD
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
=======
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
>>>>>>> f6fc9b2 (Initial commit)
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
<<<<<<< HEAD
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeOURw1OOSwnM1oibzvBZ0b2zgSaM_L9U',
    appId: '1:906066694349:web:7b2e84fb3dcaa2c36c5984',
    messagingSenderId: '906066694349',
    projectId: 'my-signup-app-9d3aa',
    authDomain: 'my-signup-app-9d3aa.firebaseapp.com',
    storageBucket: 'my-signup-app-9d3aa.firebasestorage.app',
    measurementId: 'G-MCRZ2KWMHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeIq8ZRgYL6WUQI2SngnNdINxQsI1hgjs',
    appId: '1:906066694349:android:a23d1acff9a548566c5984',
    messagingSenderId: '906066694349',
    projectId: 'my-signup-app-9d3aa',
    storageBucket: 'my-signup-app-9d3aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUn5NRdF7w2ThZFU1JRBXWYws5CcpFhzs',
    appId: '1:906066694349:ios:d2ffb866266673216c5984',
    messagingSenderId: '906066694349',
    projectId: 'my-signup-app-9d3aa',
    storageBucket: 'my-signup-app-9d3aa.firebasestorage.app',
    iosBundleId: 'com.example.mySignupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUn5NRdF7w2ThZFU1JRBXWYws5CcpFhzs',
    appId: '1:906066694349:ios:d2ffb866266673216c5984',
    messagingSenderId: '906066694349',
    projectId: 'my-signup-app-9d3aa',
    storageBucket: 'my-signup-app-9d3aa.firebasestorage.app',
    iosBundleId: 'com.example.mySignupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeOURw1OOSwnM1oibzvBZ0b2zgSaM_L9U',
    appId: '1:906066694349:web:419a5b552d4c18676c5984',
    messagingSenderId: '906066694349',
    projectId: 'my-signup-app-9d3aa',
    authDomain: 'my-signup-app-9d3aa.firebaseapp.com',
    storageBucket: 'my-signup-app-9d3aa.firebasestorage.app',
    measurementId: 'G-ZFT62FVTT9',
  );
}
=======
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6cCmZSiS6DhYkfCPv7JgT3VD5LKg9uI',
    appId: '1:251634240152:android:199b3ab91162c4f94cdeed',
    messagingSenderId: '251634240152',
    projectId: 'tubzzz-beauty',
    storageBucket: 'tubzzz-beauty.firebasestorage.app',
  );

  // iOS baad mein add karein
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6cCmZSiS6DhYkfCPv7JgT3VD5LKg9uI',
    appId: '1:251634240152:android:199b3ab91162c4f94cdeed',
    messagingSenderId: '251634240152',
    projectId: 'tubzzz-beauty',
    storageBucket: 'tubzzz-beauty.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6cCmZSiS6DhYkfCPv7JgT3VD5LKg9uI',
    appId: '1:251634240152:android:199b3ab91162c4f94cdeed',
    messagingSenderId: '251634240152',
    projectId: 'tubzzz-beauty',
    storageBucket: 'tubzzz-beauty.firebasestorage.app',
  );
}
>>>>>>> f6fc9b2 (Initial commit)
